export const AiModels: Array<{ value: string }> = [
	{ value: 'gpt-4o-mini' },
	{ value: 'gpt-4o' },
	{ value: 'gpt-4.1' },
	{ value: 'doubao-seed-2-0-pro-260215' },
	{ value: 'doubao-seed-2-0-lite-260215' },
	{ value: 'doubao-seed-2-0-mini-260215' },
	{ value: 'qwen-plus' },
	{ value: 'qwen-vl-plus' },
	{ value: 'glm-5' },
	{ value: 'glm-4.6' },
	{ value: 'glm-4.6v' },
	{ value: 'SparkDesk-v4.0' },
	{ value: 'gemini-2.5-pro' },
	{ value: 'gemini-3-pro-preview' },
	{ value: 'deepseek-chat' },
	{ value: 'deepseek-reasoner' },
	{ value: 'Pro/deepseek-ai/DeepSeek-V3' },
	{ value: 'Pro/deepseek-ai/DeepSeek-R1' },
	{ value: 'ERNIE-4.0-Turbo-8K' },
];
