export const AiModels: Array<{ value: string }> = [
	{ value: 'gpt-4o-mini' },
	{ value: 'gpt-4o' },
	{ value: 'gpt-4.1' },
	{ value: 'doubao-seed-1-6-250615' },
	{ value: 'doubao-seed-1-6-thinking-250615' },
	{ value: 'qwen-plus' },
	{ value: 'qwen-vl-plus' },
	{ value: 'qwen3-235b-a22b-instruct-2507' },
	{ value: 'qwen3-235b-a22b-thinking-2507' },
	{ value: 'SparkDesk-v4.0' },
	{ value: 'gemini-2.5-pro-exp-03-25' },
	{ value: 'deepseek-chat' },
	{ value: 'deepseek-reasoner' },
	{ value: 'Pro/deepseek-ai/DeepSeek-V3' },
	{ value: 'Pro/deepseek-ai/DeepSeek-R1' },
	{ value: 'x1' },
	{ value: 'ERNIE-4.0-Turbo-8K' },
];
